name: WordPress deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy in server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: "50.62.142.99"
          username: "root_prod@praxispharmaceutical.com.co"
          password: "Praxis123*"
          server-dir: "public_html/api_prod/"
